# Pre-commit configuration for code quality checks
# https://pre-commit.com

repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=100]
        files: \.py$
        
  # isort - Python import sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
        files: \.py$
        
  # flake8 - Python linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --extend-ignore=E203,W503]
        files: \.py$
